project:
  type: website
  title: "MCI_SBT_B_1_GID_2"
  output-dir: _site
  resources:
    - docs/iot-specs/asyncapi.yaml
    - docs/iot-specs/openapi.yaml
    - docs/iot-specs/conventions.md
    - src/raspi_firmware/settings.toml
    - src/raspi_firmware/code.py


website:
  title: "Industrial IoT"
  reader-mode: true
  page-footer:
    left: Industrial IoT 1 WiSe 2025 (MECH-M-4-IIoT)
    center: "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) Julian Huber"
    right: This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://github.com/jhumci/MECH-M-3-IIoT
  repo-url: https://github.com/jhumci/MECH-M-3-IIoT
  repo-branch: main
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: docs/Materialien.qmd
        text: Materialien
      - href: docs/Termin_1_Grundkonzepte_IoT.qmd
        text: Termin 1 Grundkonzepte IoT
      - href: docs/Termin_2_Netzwerke.qmd
        text: Termin 2 Netzwerke
      - href: docs/Termin_3_Cloud.qmd
        text: Termin 3 Cloud
      - href: docs/Dokumentation.qmd
        text: Eigene Dokumentation

format:
  html:
    theme: cosmo
    toc: true